[package]
name = "chezmoi-client"
version = "0.1.0"
edition = "2021"

[dependencies]
another-html-builder = "0.1"
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
human-number = "0.1"
