[workspace]
resolver = "2"
members = ["agent", "cache", "entity", "storage"]

[workspace.dependencies]
anyhow = { version = "1.0" }
indexmap = { version = "2.7" }
tokio = { version = "1.42" }
tracing = { version = "0.1" }
