[workspace]
members = ["./agent", "./client", "./database", "./helper", "./server"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0" }
serde = { version = "1.0" }
tokio = { version = "1.41" }
tracing = { version = "0.1" }
