[package]
name = "chezmoi-sensor-xiaomi-miflora"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license-file.workspace = true

[features]
default = ["agent"]
agent = [
    "dep:anyhow",
    "dep:bluer",
    "dep:bluer-miflora",
    "dep:serde",
    "dep:tokio",
    "chezmoi-sensor-prelude/agent",
]

[dependencies]
chezmoi-entity = { path = "../entity", features = ["serde"] }
chezmoi-sensor-prelude = { path = "../sensor-prelude" }

anyhow = { workspace = true, optional = true }
bluer = { workspace = true, features = [
    "bluetoothd",
    "serde",
], default-features = false, optional = true }
bluer-miflora = { version = "0.2", optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
tokio = { workspace = true, features = ["sync", "time"], optional = true }
tracing = { workspace = true }
