[package]
name = "chezmoi-agent"
version = "0.1.0"
edition = "2021"

[features]
default = []
bluetooth = ["dep:bluer"]

[dependencies]
chezmoi-database = { path = "../database" }
chezmoi-helper = { path = "../helper" }

anyhow = { workspace = true }
bluer = { version = "0.17", features = ["bluetoothd"], optional = true }
futures = { version = "0.3"}
tokio = { workspace = true }
tracing = { workspace = true }
sysinfo = { version = "0.32.0", default-features = false, features = [
    "system",
] }
