[package]
name = "chezmoi-agent"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license-file.workspace = true

[dependencies]
chezmoi-entity = { path = "../entity", features = ["serde"] }
chezmoi-sensor-prelude = { path = "../sensor-prelude", default-features = false, features = [
    "agent",
] }
chezmoi-sensor-system = { path = "../sensor-system", features = ["agent"] }
chezmoi-sensor-xiaomi-atc = { path = "../sensor-xiaomi-atc", default-features = false, features = [
    "agent",
] }
chezmoi-sensor-xiaomi-miflora = { path = "../sensor-xiaomi-miflora", default-features = false, features = [
    "agent",
] }

anyhow = { workspace = true }
bluer = { workspace = true, features = [
    "bluetoothd",
    "serde",
], default-features = false }
futures = { version = "0.3" }
indexmap = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["indexmap"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
reqwest = { version = "0.12", default-features = false, features = ["json"] }
